---
layout: cv
title: Arturo Cruz's CV
---
# Arturo Cruz
**Accounting Major with Minor in Business Analytics**

**Email**: [c.arturocruz8@gmail.com](mailto:c.arturocruz8@gmail.com)  
**Phone**: 815-661-1886  
**LinkedIn**: [www.linkedin.com/in/arturo-cruz-p0145](https://www.linkedin.com/in/arturo-cruz-p0145)

---

## Education

**Bachelor of Science in Accounting** – Minor in Business Analytics  
Brigham Young University–Idaho, Rexburg, ID  
*Expected Graduation*: April 2025  
- GPA: 3.58  
- Area of interest: Audit/Assurance  

### Leadership Roles
- **Student Accounting Society, President** (Jan. 2023 – Aug. 2023)  
- **Student Accounting Society, Chief PR Officer** (Apr. 2022 – Dec. 2022)  
- **Full-Time Missionary/Door-to-Door Representative** (Oct. 2018 – Oct. 2020)  

---

## Experience

### **Audit/Assurance Intern**  
**RSM US LLC** – Dallas, TX  
*Jan. 2024 – Mar. 2024*  
- Assisted senior auditors in conducting financial audits, ensuring compliance with GAAP and relevant regulations.  
- Demonstrated proficiency in using audit software and tools such as Excel and IDEA to perform data analysis and testing procedures.  
- Communicated audit findings and recommendations to engagement team members and client management.

### **Income Taxation Tutor**  
**Brigham Young University - Idaho** – Rexburg, ID  
*Sept. 2023 – Dec. 2023*  
- Crafted personalized review plans for individual students, enhancing preparation for income taxation exams.  
- Worked with students one-on-one to set and meet personalized goals, ensuring a greater understanding of taxation concepts.

### **Sales Associate and Lowes Pro Online Order Coordinator**  
**Lowe’s Home Improvement** – Idaho Falls, ID  
*Jul. 2021 – Sept. 2023*  
- Delivered daily high-quality customer service in store and over the phone.  
- Executed customer orders through technology in a high-paced environment.  
- Worked closely with others to ensure quick and accurate completion of high-profile customer orders.

---

## Skills

- Bilingual: English (Fluent), Spanish (Fluent)  
- Proficient in Microsoft Excel  
- Proficient and experienced with IDEA  
- Academic training in SQL, Python, Tableau, Power BI
